# Generated by Django 4.1.7 on 2023-03-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guerrilla_television', '0003_guerrillatelevisionitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guerrillatelevisionitem',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
