# Generated by Django 4.1.7 on 2023-03-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guerrilla_television', '0004_guerrillatelevisionitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guerrillatelevisionitem',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
