# Generated by Django 4.1.7 on 2023-03-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guerrilla_television', '0006_alter_category_id_alter_collection_id_alter_genre_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
