# Generated by Django 4.1.7 on 2023-03-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guerrilla_television', '0009_alter_guerrillatelevisionitem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guerrillatelevisionitem',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='guerrilla_television.category'),
        ),
        migrations.AlterField(
            model_name='guerrillatelevisionitem',
            name='collections',
            field=models.ManyToManyField(blank=True, null=True, to='guerrilla_television.collection'),
        ),
        migrations.AlterField(
            model_name='guerrillatelevisionitem',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='guerrilla_television.genre'),
        ),
        migrations.AlterField(
            model_name='guerrillatelevisionitem',
            name='languages',
            field=models.ManyToManyField(blank=True, null=True, to='guerrilla_television.language'),
        ),
        migrations.AlterField(
            model_name='guerrillatelevisionitem',
            name='producers',
            field=models.ManyToManyField(blank=True, null=True, to='guerrilla_television.producer'),
        ),
        migrations.AlterField(
            model_name='guerrillatelevisionitem',
            name='production_dates',
            field=models.ManyToManyField(blank=True, null=True, to='guerrilla_television.productiondate'),
        ),
        migrations.AlterField(
            model_name='guerrillatelevisionitem',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='guerrilla_television.tag'),
        ),
        migrations.AlterField(
            model_name='guerrillatelevisionitem',
            name='urls',
            field=models.ManyToManyField(blank=True, null=True, to='guerrilla_television.url'),
        ),
    ]
